In [1]:
import numpy as np

In [2]:
# Matrix is subset of array
# functions ones and zeros only
# 4*4 Identity matrix

In [3]:
range(10)

range(0, 10)

In [4]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list(range(3,10))

[3, 4, 5, 6, 7, 8, 9]

In [5]:
list(float(range(3,10)))

TypeError: float() argument must be a string or a number, not 'range'

In [6]:
list(range(3,10.6))

TypeError: 'float' object cannot be interpreted as an integer

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0.5,10) # generates floating numbers

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [9]:
np.arange(5,-4,-1)

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3])

In [10]:
np.arange(5,-4,-0.5)

array([ 5. ,  4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ,
       -0.5, -1. , -1.5, -2. , -2.5, -3. , -3.5])

In [11]:
list(range(-4,1))

[-4, -3, -2, -1, 0]

In [12]:
arr = np.random.rand(4,5)

In [13]:
arr

array([[0.07466566, 0.59975196, 0.82157649, 0.32030892, 0.88489502],
       [0.99409693, 0.26545021, 0.15516256, 0.24146288, 0.44249176],
       [0.25899777, 0.45184047, 0.59369555, 0.2811132 , 0.83572534],
       [0.90096677, 0.10382207, 0.17605468, 0.48818884, 0.24869385]])

In [14]:
arr>0.5

array([[False,  True,  True, False,  True],
       [ True, False, False, False, False],
       [False, False,  True, False,  True],
       [ True, False, False, False, False]])

In [16]:
arr[arr>0.5]

array([0.59975196, 0.82157649, 0.88489502, 0.99409693, 0.59369555,
       0.83572534, 0.90096677])

In [18]:
np.linspace(1,5,20) # gives 20 numbers in range 0f 1 - 5

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [19]:
list(np.linspace(1,5,20))

[1.0,
 1.2105263157894737,
 1.4210526315789473,
 1.631578947368421,
 1.8421052631578947,
 2.052631578947368,
 2.263157894736842,
 2.473684210526316,
 2.6842105263157894,
 2.894736842105263,
 3.1052631578947367,
 3.3157894736842106,
 3.526315789473684,
 3.7368421052631575,
 3.9473684210526314,
 4.157894736842105,
 4.368421052631579,
 4.578947368421052,
 4.789473684210526,
 5.0]

In [20]:
np.linspace(1,5,20,retstep=True)

(array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
        2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
        3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
        4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]),
 0.21052631578947367)

In [22]:
np.logspace(1,50,10) #log values of 1-50  with 10 values with base = 10

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.zeros(3,5)

TypeError: Cannot interpret '5' as a data type

In [28]:
np.zeros((3,5,2)) # represented as 3-D axis with 5*2 matrix with 3 sets

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [30]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [32]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [33]:
np.ones((3,2,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [34]:
np.ones((3,2,5)) *8 # functions ones and zeros only

array([[[8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.]],

       [[8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.]],

       [[8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.]]])

In [39]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.empty((4,3))

array([[0.00000000e+000, 2.47032823e-322, 0.00000000e+000],
       [0.00000000e+000, 2.10077583e-312, 5.74084271e+169],
       [7.17594811e-091, 3.05934421e-057, 4.29400717e-038],
       [6.45373003e-067, 3.99910963e+252, 6.80146329e-310]])

In [41]:
np.eye(4) # 4*4 Identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
a = np.eye(4) # 4*4 Identity matrix

In [44]:
a.shape # dimension

(4, 4)

In [45]:
a.size #. no of elements

16

In [46]:
a.ndim # 2-D dimension

2

# slicing and indices operation

In [17]:
a1 = np.random.randn(3,4)

In [18]:
a1

array([[-0.03572079,  0.91569799,  0.66004055, -2.45840017],
       [ 0.06177958,  0.60361796,  0.30455474,  0.82127155],
       [ 0.66148251, -0.12136801,  0.42867147, -0.3683597 ]])

In [19]:
import pandas as pd

In [20]:
pd.DataFrame(a1)

0         1         2         3
0 -0.035721  0.915698  0.660041 -2.458400
1  0.061780  0.603618  0.304555  0.821272
2  0.661483 -0.121368  0.428671 -0.368360

In [21]:
a1

array([[-0.03572079,  0.91569799,  0.66004055, -2.45840017],
       [ 0.06177958,  0.60361796,  0.30455474,  0.82127155],
       [ 0.66148251, -0.12136801,  0.42867147, -0.3683597 ]])

In [22]:
a1[2][2]

0.42867146500004394

In [23]:
a1[1][1]

0.6036179599560014

In [24]:
a1[0:2,0:2]

array([[-0.03572079,  0.91569799],
       [ 0.06177958,  0.60361796]])

In [25]:
a1[[0,1],0:2]

array([[-0.03572079,  0.91569799],
       [ 0.06177958,  0.60361796]])

In [26]:
a1

array([[-0.03572079,  0.91569799,  0.66004055, -2.45840017],
       [ 0.06177958,  0.60361796,  0.30455474,  0.82127155],
       [ 0.66148251, -0.12136801,  0.42867147, -0.3683597 ]])

In [27]:
a2 = a1

In [28]:
a2

array([[-0.03572079,  0.91569799,  0.66004055, -2.45840017],
       [ 0.06177958,  0.60361796,  0.30455474,  0.82127155],
       [ 0.66148251, -0.12136801,  0.42867147, -0.3683597 ]])

In [30]:
a2[0][0] = 2.3

In [31]:
a2

array([[ 2.3       ,  0.91569799,  0.66004055, -2.45840017],
       [ 0.06177958,  0.60361796,  0.30455474,  0.82127155],
       [ 0.66148251, -0.12136801,  0.42867147, -0.3683597 ]])

In [64]:
a1[[1,2],3]

array([ 0.3258348 , -1.93216611])

In [67]:
np.random.randint(1,3,(3,3))

array([[2, 1, 1],
       [2, 2, 1],
       [2, 1, 2]])

In [32]:
m1 = np.random.randint(1,3,(3,3))

In [33]:
m1

array([[2, 2, 2],
       [1, 1, 1],
       [2, 2, 2]])

In [34]:
m2 = np.random.randint(2,4,(3,3))

In [35]:
m2

array([[2, 3, 3],
       [2, 3, 2],
       [3, 3, 3]])

In [36]:
m1*m2  # no a matrix multiplication , just a elelment-wise multiplication

array([[4, 6, 6],
       [2, 3, 2],
       [6, 6, 6]])

In [37]:
m1@m2 # a matrix multiplication

array([[14, 18, 16],
       [ 7,  9,  8],
       [14, 18, 16]])

In [38]:
m = m1@m2

In [39]:
m/0 #gives inf instead 

/var/folders/sd/ksvjn1650sbfvdvzr8hdh84c0000gn/T/ipykernel_14815/3791875896.py:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [40]:
1/0

ZeroDivisionError: division by zero

In [74]:
pow(m1,2)

array([[4, 1, 4],
       [4, 1, 4],
       [4, 1, 1]])

In [75]:
np.sqrt(m1)

array([[1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.        , 1.        ]])

In [76]:
np.log(m1)

array([[0.69314718, 0.        , 0.69314718],
       [0.69314718, 0.        , 0.69314718],
       [0.69314718, 0.        , 0.        ]])

In [77]:
np.log10(m1)

array([[0.30103, 0.     , 0.30103],
       [0.30103, 0.     , 0.30103],
       [0.30103, 0.     , 0.     ]])

In [78]:
np.exp(m1)

array([[7.3890561 , 2.71828183, 7.3890561 ],
       [7.3890561 , 2.71828183, 7.3890561 ],
       [7.3890561 , 2.71828183, 2.71828183]])

In [79]:
m1**2 # power function

array([[4, 1, 4],
       [4, 1, 4],
       [4, 1, 1]])